### ISSUE TITLE
Custom SPI pins

### ISSUE THREAD

**Issue by biemster** [akshayabali/pico-lora#12]
The README mentions it is possible to reconfigure the SPI pins on the rp2040, but the official documentation seems to refute that mentioning that the hardware spi pins are fixed.
Testing on different pins indeed does not seem to work, should this be changed in the readme?

There is a way though this might work, using PIO SPI. I'm currently trying to build this, as I am pin constrained here.

**Comment by akshayabali** [comment]
The Pi Pico board has two SPI devices. This would give you the ability to switch between them. Also, the pin mapping of these two  devices can be chosen from a fixed set defined in the datasheet.

Thanks for mentioning this, I'll update the Readme to make it more clearer.

![pinout.png](https://github.com/akshayabali/pico-lora/assets/11997625/6a72ea04-cd7b-4d06-bfba-766271ce3e92)

**Comment by biemster** [comment]
I actually just got fully custom pins working with the PIO SPI, care for a PR?

**Comment by akshayabali** [comment]
That sounds great.

PRs are always welcome.
