### ISSUE TITLE
LoRaClass::onReceive vs parsePacket

### ISSUE THREAD

**Issue by tomicooler** [akshayabali/pico-lora#3]
Hi!

I started to use the library, it works with my setup (Pico  + RFM95W module), but I have some small issues with onReceive and parsePacket methods.

1. the onReceive() method calls my callback only 1 time, even if I set the callback again and put the lora class to receive() mode. I used usb for debug messages, not sure if that interferes it with somehow.
2. when I use the parsePacket() in a loop, every message is duplicated. The sender is OK, because every message is duplicated not only my messages.

Any idea about the issues? Thanks.

BTW the ack might be missing from the callback:
```
 void LoRaClass::onDio0Rise(uint gpio, uint32_t events)
 {
+  gpio_acknowledge_irq(gpio, events);
   LoRa.handleDio0Rise();
 }

```

**Comment by akshayabali** [comment]
Hi @tomicooler,

Are you able to debug the dio0 pin? is there an interrupt signal?

**Comment by tomicooler** [comment]
Hi @akshayabali,

I will try to debug the dio0 pin, but first I need to create one more Pico with a LoRa module, it will take some time.

**Comment by akshayabali** [comment]
Hi @tomicooler,

I've merged the pull request. I hope it fixes it.
