### ISSUE TITLE
Garbage received data

### ISSUE THREAD

**Issue by nachobacanful** [akshayabali/pico-lora#5]
I am using this chip https://www.aliexpress.com/item/2251832798340884.html?spm=a2g0o.order_list.0.0.25111802u8HKXd&gatewayAdapt=4itemAdapt

I have double checked all the connections and pins in the script. I am trying to set this up initially, and I can't even get the duplex example to work. Regardless of frequency, I set 915 or 868 MHz, but I still get garbage output on the receiving end. 

Is there a way I can further troubleshoot this? I have edited the code to output the transmission `HeLoRa World!` and I get the following in the receiving end:

```
�C`A`pG�T-�     berry Pi Trading LtdA`pG�T-�    rading Ltd-�    Raspberry Pi Trading Ltd�B�C�0�B��pG0����Frading Ltding Ltdi Trading Ltdpberry Pi Trading Ltd�C�0�B��pG0����F
```

Not sure if it's related to either the transmitting side or receiving side. How can I troubleshoot this?

perhaps I missed some baud configuration or something...

**Comment by nachobacanful** [comment]
I have also tried 434mhz assuming that the listing where I bought the radios is wrong, and same result

**Comment by nachobacanful** [comment]
I forgot to mention context, I have two picos with a LoRa chip each. 
Here is the register dumps (at 915Mhz):
```
LoRa Dump Registers
0x0: 0xbc
0x1: 0x81
0x2: 0x1a
0x3: 0xb
0x4: 0x0
0x5: 0x52
0x6: 0xe4
0x7: 0xc0
0x8: 0x0
0x9: 0x8f
0xa: 0x9
0xb: 0x2b
0xc: 0x23
0xd: 0x1
0xe: 0x0
0xf: 0x0
0x10: 0x0
0x11: 0x0
0x12: 0x0
0x13: 0x0
0x14: 0x0
0x15: 0x0
0x16: 0x0
0x17: 0x0
0x18: 0x10
0x19: 0x0
0x1a: 0x0
0x1b: 0x0
0x1c: 0x0
0x1d: 0x72
0x1e: 0x70
0x1f: 0x64
0x20: 0x0
0x21: 0x8
0x22: 0x1
0x23: 0xff
0x24: 0x0
0x25: 0x0
0x26: 0x4
0x27: 0x0
0x28: 0x0
0x29: 0x0
0x2a: 0x0
0x2b: 0x0
0x2c: 0x0
0x2d: 0x50
0x2e: 0x14
0x2f: 0x45
0x30: 0x55
0x31: 0xc3
0x32: 0x5
0x33: 0x27
0x34: 0x1c
0x35: 0xa
0x36: 0x3
0x37: 0xa
0x38: 0x42
0x39: 0x12
0x3a: 0x49
0x3b: 0x1d
0x3c: 0x0
0x3d: 0xaf
0x3e: 0x0
0x3f: 0x0
0x40: 0x0
0x41: 0x0
0x42: 0x12
0x43: 0x24
0x44: 0x2d
0x45: 0x0
0x46: 0x3
0x47: 0x0
0x48: 0x4
0x49: 0x23
0x4a: 0x0
0x4b: 0x9
0x4c: 0x5
0x4d: 0x84
0x4e: 0x32
0x4f: 0x2b
0x50: 0x14
0x51: 0x0
0x52: 0x0
0x53: 0xf
0x54: 0x0
0x55: 0x0
0x56: 0x0
0x57: 0xf
0x58: 0xe0
0x59: 0x0
0x5a: 0xc
0x5b: 0x0
0x5c: 0x7
0x5d: 0x0
0x5e: 0x5c
0x5f: 0x78
0x60: 0x0
0x61: 0x1c
0x62: 0xe
0x63: 0x5b
0x64: 0xcc
0x65: 0x0
0x66: 0x1
0x67: 0x50
0x68: 0x0
0x69: 0x0
0x6a: 0x0
0x6b: 0x0
0x6c: 0x0
0x6d: 0x0
0x6e: 0x0
0x6f: 0xb
0x70: 0xd0
0x71: 0x0
0x72: 0x13
0x73: 0x0
0x74: 0x0
0x75: 0x0
0x76: 0x0
0x77: 0x0
0x78: 0x0
0x79: 0x0
0x7a: 0x0
0x7b: 0x0
0x7c: 0x0
0x7d: 0x0
0x7e: 0x0
0x7f: 0x0

```

```
LoRa Dump Registers
0x0: 0x8
0x1: 0x81
0x2: 0x1a
0x3: 0xb
0x4: 0x0
0x5: 0x52
0x6: 0xe4
0x7: 0xc0
0x8: 0x0
0x9: 0x8f
0xa: 0x9
0xb: 0x2b
0xc: 0x23
0xd: 0x1
0xe: 0x0
0xf: 0x0
0x10: 0x0
0x11: 0x0
0x12: 0x0
0x13: 0x0
0x14: 0x0
0x15: 0x0
0x16: 0x0
0x17: 0x0
0x18: 0x10
0x19: 0x0
0x1a: 0x0
0x1b: 0x0
0x1c: 0x0
0x1d: 0x72
0x1e: 0x70
0x1f: 0x64
0x20: 0x0
0x21: 0x8
0x22: 0x1
0x23: 0xff
0x24: 0x0
0x25: 0x0
0x26: 0x4
0x27: 0x0
0x28: 0x0
0x29: 0x0
0x2a: 0x0
0x2b: 0x0
0x2c: 0x0
0x2d: 0x50
0x2e: 0x14
0x2f: 0x45
0x30: 0x55
0x31: 0xc3
0x32: 0x5
0x33: 0x27
0x34: 0x1c
0x35: 0xa
0x36: 0x3
0x37: 0xa
0x38: 0x42
0x39: 0x12
0x3a: 0x49
0x3b: 0x1d
0x3c: 0x0
0x3d: 0xaf
0x3e: 0x0
0x3f: 0x0
0x40: 0x0
0x41: 0x0
0x42: 0x12
0x43: 0x24
0x44: 0x2d
0x45: 0x0
0x46: 0x3
0x47: 0x0
0x48: 0x4
0x49: 0x23
0x4a: 0x0
0x4b: 0x9
0x4c: 0x5
0x4d: 0x84
0x4e: 0x32
0x4f: 0x2b
0x50: 0x14
0x51: 0x0
0x52: 0x0
0x53: 0xf
0x54: 0x0
0x55: 0x0
0x56: 0x0
0x57: 0xf
0x58: 0xe0
0x59: 0x0
0x5a: 0xc
0x5b: 0x0
0x5c: 0x8
0x5d: 0x0
0x5e: 0x5c
0x5f: 0x78
0x60: 0x0
0x61: 0x1c
0x62: 0xe
0x63: 0x5b
0x64: 0xcc
0x65: 0x0
0x66: 0x1
0x67: 0x50
0x68: 0x0
0x69: 0x0
0x6a: 0x0
0x6b: 0x0
0x6c: 0x0
0x6d: 0x0
0x6e: 0x0
0x6f: 0xb
0x70: 0xd0
0x71: 0x0
0x72: 0x14
0x73: 0x0
0x74: 0x0
0x75: 0x0
0x76: 0x0
0x77: 0x0
0x78: 0x0
0x79: 0x0
0x7a: 0x0
0x7b: 0x0
0x7c: 0x0
0x7d: 0x0
0x7e: 0x0
0x7f: 0x0
```

**Comment by nachobacanful** [comment]
Further troubleshooting revealed that both radios can transmit and receive correctly, I have verified using this https://github.com/wdomski/LoRa-RaspberryPi project as the receiver and the code in the loraduplex.cpp.

Here is another project's  receiving code working:
![Uploading Screenshot_20220718_214337.png…]()


This further confirms that transmitting works correctly, but receiving seems to either garble up or the code reads memory that is not supposed to. This however does not mean the transmission is wrong.

**Comment by nachobacanful** [comment]
@akshayabali do you know of a way i can troubleshoot this without much effort? perhaps I can overload the read/write register functions so that they verify memory values when writing so  can see if there is any issues there. I don't know much about the lora hardware API so I will have to read the [datasheet](https://www.mouser.com/datasheet/2/761/sx1276-1278113.pdf) before I can start troubleshooting this for reals.

**Comment by Rio-Song-kr** [comment]
@nachobacanful 
-  LoRaReceiver.cpp

From
```C++
// read packet
while (LoRa.available()) {
  printf((char*)LoRa.read());
}
```
To 
```C++
// read packet
while (LoRa.available()) {
  printf("%c", (char*)LoRa.read());
}
```

-  LoRaReceiverCallback.cpp

From
```C++
// read packet
while (LoRa.available()) {
  printf("%s", (char*)LoRa.read());
}
```
To 
```C++
// read packet
while (LoRa.available()) {
  printf("%c", (char*)LoRa.read());
}
```
and add while(1);
```C++
// put the radio into receive mode
  LoRa.receive();
  while(1);
  return 0;
```

After modifying as above, it was confirmed that it works normally in two picos with 500MHz

**Comment by nachobacanful** [comment]
@Rio-Song-kr That work for the simplex example. How would that work for the duplex example? 
seems like the data is garbled even before its printed(which wring usge of printf seems to be the problem with the other codes) since `incomingLength != sizeof(incoming))` triggers, 
meaning the data is not being received correctly or correctly casted back to the original types

**Comment by nachobacanful** [comment]
Here is an image to back the above statement 
![Screenshot_20220914_195103](https://user-images.githubusercontent.com/13954480/190302985-08dbf6ff-0652-4865-8b64-619e5b7cf388.png)

**Comment by nachobacanful** [comment]
I discovered that there are many errors in the code regarding what information is sent. Resolving the information that is sent and using c strings instead of Strings fixes the issue. 

@Rio-Song-kr  Thanks for the help!
