### ISSUE TITLE
RP2040 MicroMod w/ MicroMod Lora infinite loops

### ISSUE THREAD

**Issue by Python380** [akshayabali/pico-lora#7]
Multiple places either crash or have garbage values on the MicroMod Lora and RP2040 processor board.
So far, I have narrowed down a single problem area (though I know that there are more than that):
* endPacket() will infinite loop, effectively crashing the pico (note: in async mode, it doesn't enter an infinite loop, but I have not verified if it sends data or not)

Hardware: using MicroMod RP2040 with MicroMod Function Lora. This is in function board slot 0.

the tutorial on how to use it (which unfortunately uses the mbed core for the rp2040, which I don't want to use): https://learn.sparkfun.com/tutorials/1w-lora-micromod-function-board-hookup-guide/all#peer-to-peer-example

I am for sure (checked it like 3 times) that the pins are defined properly in my code - https://github.com/Python380/RP2040MicroModLoRa. Sorry for not making a fork (didn't think I would need to)

**Comment by akshayabali** [comment]
Hi @Python380 
Can you try reading the value of the REG_IRQ_FLAGS Register and check if appropriate flags are set correctly?
Also, please share the code snippet you are running, or are you using an example code? I'll try if I can recreate the issue.

For other issues, I wrote the code using pico-sdk which handles printf function differently. Check the solution mentioned in [this](https://github.com/akshayabali/pico-lora/issues/5#issuecomment-1236275531) post once, if it solves your issue.

If you are able to solve the issue, please create a pull request so it no one else faces any issues.

**Comment by Python380** [comment]
Register dump immediately after starting looks like this:
```text
*** SENDER ***

0x0: 0x9
0x1: 0x81
0x2: 0x1a
0x3: 0xb
0x4: 0x0
0x5: 0x52
0x6: 0xe4
0x7: 0xc0
0x8: 0x0
0x9: 0x8f
0xa: 0x9
0xb: 0x2b
0xc: 0x23
0xd: 0x1
0xe: 0x0
0xf: 0x0
0x10: 0x0
0x11: 0x0
0x12: 0x0
0x13: 0x0
0x14: 0x0
0x15: 0x0
0x16: 0x0
0x17: 0x0
0x18: 0x10
0x19: 0x0
0x1a: 0x0
0x1b: 0x0
0x1c: 0x0
0x1d: 0x72
0x1e: 0x70
0x1f: 0x64
0x20: 0x0
0x21: 0x8
0x22: 0x1
0x23: 0xff
0x24: 0x0
0x25: 0x0
0x26: 0x4
0x27: 0x0
0x28: 0x0
0x29: 0x0
0x2a: 0x0
0x2b: 0x0
0x2c: 0x0
0x2d: 0x50
0x2e: 0x14
0x2f: 0x45
0x30: 0x55
0x31: 0xc3
0x32: 0x5
0x33: 0x27
0x34: 0x1c
0x35: 0xa
0x36: 0x3
0x37: 0xa
0x38: 0x42
0x39: 0x12
0x3a: 0x49
0x3b: 0x1d
0x3c: 0x0
0x3d: 0xaf
0x3e: 0x0
0x3f: 0x0
0x40: 0x0
0x41: 0x0
0x42: 0x12
0x43: 0x24
0x44: 0x2d
0x45: 0x0
0x46: 0x3
0x47: 0x0
0x48: 0x4
0x49: 0x23
0x4a: 0x0
0x4b: 0x9
0x4c: 0x5
0x4d: 0x84
0x4e: 0x32
0x4f: 0x2b
0x50: 0x14
0x51: 0x0
0x52: 0x0
0x53: 0x10
0x54: 0x0
0x55: 0x0
0x56: 0x0
0x57: 0xf
0x58: 0xe0
0x59: 0x0
0x5a: 0xc
0x5b: 0x0
0x5c: 0x7
0x5d: 0x0
0x5e: 0x5c
0x5f: 0x78
0x60: 0x0
0x61: 0x1c
0x62: 0xe
0x63: 0x5b
0x64: 0xcc
0x65: 0x0
0x66: 0x1
0x67: 0x50
0x68: 0x0
0x69: 0x0
0x6a: 0x0
0x6b: 0x0
0x6c: 0x0
0x6d: 0x0
0x6e: 0x0
0x6f: 0xb
0x70: 0xd0
0x71: 0x0
0x72: 0x13
0x73: 0x0
0x74: 0x0
0x75: 0x0
0x76: 0x0
0x77: 0x0
0x78: 0x0
0x79: 0x0
0x7a: 0x0
0x7b: 0x0
0x7c: 0x0
0x7d: 0x0
0x7e: 0x0
0x7f: 0x0

*** RECEIVER ***

0x0: 0x40
0x1: 0x81
0x2: 0x1a
0x3: 0xb
0x4: 0x0
0x5: 0x52
0x6: 0xe4
0x7: 0xc0
0x8: 0x0
0x9: 0x8f
0xa: 0x9
0xb: 0x2b
0xc: 0x23
0xd: 0x1
0xe: 0x0
0xf: 0x0
0x10: 0x0
0x11: 0x0
0x12: 0x0
0x13: 0x0
0x14: 0x0
0x15: 0x0
0x16: 0x0
0x17: 0x0
0x18: 0x10
0x19: 0x0
0x1a: 0x0
0x1b: 0x0
0x1c: 0x0
0x1d: 0x72
0x1e: 0x70
0x1f: 0x64
0x20: 0x0
0x21: 0x8
0x22: 0x1
0x23: 0xff
0x24: 0x0
0x25: 0x0
0x26: 0x4
0x27: 0x0
0x28: 0x0
0x29: 0x0
0x2a: 0x0
0x2b: 0x0
0x2c: 0x0
0x2d: 0x50
0x2e: 0x14
0x2f: 0x45
0x30: 0x55
0x31: 0xc3
0x32: 0x5
0x33: 0x27
0x34: 0x1c
0x35: 0xa
0x36: 0x3
0x37: 0xa
0x38: 0x42
0x39: 0x12
0x3a: 0x49
0x3b: 0x1d
0x3c: 0x0
0x3d: 0xaf
0x3e: 0x0
0x3f: 0x0
0x40: 0x0
0x41: 0x0
0x42: 0x12
0x43: 0x24
0x44: 0x2d
0x45: 0x0
0x46: 0x3
0x47: 0x0
0x48: 0x4
0x49: 0x23
0x4a: 0x0
0x4b: 0x9
0x4c: 0x5
0x4d: 0x84
0x4e: 0x32
0x4f: 0x2b
0x50: 0x14
0x51: 0x0
0x52: 0x0
0x53: 0xf
0x54: 0x0
0x55: 0x0
0x56: 0x0
0x57: 0xf
0x58: 0xe0
0x59: 0x0
0x5a: 0xc
0x5b: 0x0
0x5c: 0x7
0x5d: 0x0
0x5e: 0x5c
0x5f: 0x78
0x60: 0x0
0x61: 0x1c
0x62: 0xe
0x63: 0x5b
0x64: 0xcc
0x65: 0x0
0x66: 0x1
0x67: 0x50
0x68: 0x0
0x69: 0x0
0x6a: 0x0
0x6b: 0x0
0x6c: 0x0
0x6d: 0x0
0x6e: 0x0
0x6f: 0xb
0x70: 0xd0
0x71: 0x0
0x72: 0x13
0x73: 0x0
0x74: 0x0
0x75: 0x0
0x76: 0x0
0x77: 0x0
0x78: 0x0
0x79: 0x0
0x7a: 0x0
0x7b: 0x0
0x7c: 0x0
0x7d: 0x0
0x7e: 0x0
0x7f: 0x0
```

In both cases, the radio seems to start successfully.
In the repo I mentioned in the issue, I am using the sender and receiver examples, both of which are modified in ways I probably haven't documented. The main library has also been modified slightly (I can't remember what I changed and what I didn't in the main library)

**Comment by Python380** [comment]
I am starting my radios at 915E6, could you explain why the preset was 500E6?

Do you have examples of what the SPX1276 registers should look like?

**Comment by Python380** [comment]
sorry - SX1276

**Comment by Python380** [comment]
The data sheet that I found seems to indicate that the module is in standby...

register 0x01 = 0x81 = 0b10000001
* bit 7: LoRa: 1
* bits 6-5: Modulation: FSK
* rsvd
* bit 3: low frequency: 0
* bit 2-0: mode: 001 (standby)

**
![image](https://user-images.githubusercontent.com/74334918/204412443-e4bb8ff6-6572-4204-81e9-b9d2e86468f5.png)
**
Is this normal?

**Comment by Python380** [comment]
Or in LoRa specific section, its the same outcome, but some bits mean different things:
![image](https://user-images.githubusercontent.com/74334918/204413152-1bb40c35-9b4f-4518-b3f1-1538bd6a0719.png)

**Comment by Python380** [comment]
All of the register addresses are the same as datasheet - can't really find anything else out of the ordinary...

**Comment by Python380** [comment]
Got transmit to supposedly work... My module required some additional changes to the code. It has RX & TX trigger/enable pins to make the module transmit and/or receive.

Unfortunately, I was unable to get receive to work properly yet.

**Comment by Python380** [comment]
known good Arduino MBed core code does not receive transmissions

**Comment by akshayabali** [comment]
Some people were having issues with RX coz the printf type handling wasn't correct and was seeing garbage data when reading.

**Comment by Python380** [comment]
Fixing the printf type handling didn't help...
